/*================================================
	カテゴリ情報テーブル作成スクリプト
================================================*/

DROP TABLE T_CAMARTICLE;

CREATE TABLE T_CAMARTICLE (
	CA_ID		SERIAL	not null primary key,
	CA_CLID		INTEGER,
	CA_STAT		INTEGER,
	CA_CATEID	INTEGER,
	CA_TITLE	TEXT,
	CA_IMG		TEXT,
	CA_IMGORG	TEXT,
	CA_CONTENTS	TEXT,
	CA_DISPNO	INTEGER,
	CA_ADMINID	INTEGER,
	CA_INSDATE	TIMESTAMP,
	CA_UPDDATE	TIMESTAMP,
	CA_DELDATE	TIMESTAMP,
	CA_YOBI1	TEXT,
	CA_YOBI2	TEXT,
	CA_YOBI3	TEXT,
	CA_YOBI4	TEXT,
	CA_YOBI5	TEXT
);

REVOKE all ON T_CAMARTICLE FROM public;

CREATE INDEX CA_IDX_01 ON T_CAMARTICLE USING btree( CA_ID );
CREATE INDEX CA_IDX_02 ON T_CAMARTICLE USING btree( CA_CLID );
CREATE INDEX CA_IDX_03 ON T_CAMARTICLE USING btree( CA_STAT );
CREATE INDEX CA_IDX_04 ON T_CAMARTICLE USING btree( CA_CATEID );
CREATE INDEX CA_IDX_05 ON T_CAMARTICLE USING btree( CA_DISPNO );
CREATE INDEX CA_IDX_06 ON T_CAMARTICLE USING btree( CA_ADMINID );
CREATE INDEX CA_IDX_07 ON T_CAMARTICLE USING btree( CA_INSDATE );
CREATE INDEX CA_IDX_08 ON T_CAMARTICLE USING btree( CA_UPDDATE );
CREATE INDEX CA_IDX_09 ON T_CAMARTICLE USING btree( CA_DELDATE );
