/*================================================
	沿線駅マスタテーブル作成スクリプト
================================================*/

DROP TABLE M_STATION;

CREATE TABLE M_STATION (
	ST_AREACD	integer,
	ST_AREA		text,
	ST_PREFCD	integer,
	ST_PREF		text,
	ST_LINECD	integer,
	ST_LINE		text,
	ST_LINEKANA	text,
	ST_STACD	integer,
	ST_STA		text,
	ST_STAKANA	text,
	ST_YOBI1	text,
	ST_YOBI2	text,
	ST_YOBI3	text,
	ST_YOBI4	text,
	ST_YOBI5	text
);

REVOKE all ON M_STATION FROM public;

CREATE INDEX ST_IDX_01 ON M_STATION USING btree( ST_AREACD );
CREATE INDEX ST_IDX_02 ON M_STATION USING btree( ST_AREA );
CREATE INDEX ST_IDX_03 ON M_STATION USING btree( ST_PREFCD );
CREATE INDEX ST_IDX_04 ON M_STATION USING btree( ST_PREF );
CREATE INDEX ST_IDX_05 ON M_STATION USING btree( ST_LINECD );
CREATE INDEX ST_IDX_06 ON M_STATION USING btree( ST_LINE );
CREATE INDEX ST_IDX_07 ON M_STATION USING btree( ST_LINEKANA );
CREATE INDEX ST_IDX_08 ON M_STATION USING btree( ST_STACD );
CREATE INDEX ST_IDX_09 ON M_STATION USING btree( ST_STA );
CREATE INDEX ST_IDX_10 ON M_STATION USING btree( ST_STAKANA );
