/*================================================
	カテゴリ情報テーブル作成スクリプト
================================================*/

DROP TABLE T_ADMISSION;

CREATE TABLE T_ADMISSION (
	AS_ID		SERIAL	not null primary key,
	AS_CLID		INTEGER,
	AS_STAT		INTEGER,
	AS_CGID		INTEGER,
	AS_TITLE	TEXT,
	AS_IMG		TEXT,
	AS_IMGORG	TEXT,
	AS_CONTENTS	TEXT,
	AS_DISPNO	INTEGER,
	AS_ADMINID	INTEGER,
	AS_INSDATE	TIMESTAMP,
	AS_UPDDATE	TIMESTAMP,
	AS_DELDATE	TIMESTAMP,
	AS_YOBI1	TEXT,
	AS_YOBI2	TEXT,
	AS_YOBI3	TEXT,
	AS_YOBI4	TEXT,
	AS_YOBI5	TEXT
);

REVOKE all ON T_ADMISSION FROM public;

CREATE INDEX AS_IDX_01 ON T_ADMISSION USING btree( AS_ID );
CREATE INDEX AS_IDX_02 ON T_ADMISSION USING btree( AS_CLID );
CREATE INDEX AS_IDX_03 ON T_ADMISSION USING btree( AS_STAT );
CREATE INDEX AS_IDX_04 ON T_ADMISSION USING btree( AS_CGID );
CREATE INDEX AS_IDX_05 ON T_ADMISSION USING btree( AS_DISPNO );
CREATE INDEX AS_IDX_06 ON T_ADMISSION USING btree( AS_ADMINID );
CREATE INDEX AS_IDX_07 ON T_ADMISSION USING btree( AS_INSDATE );
CREATE INDEX AS_IDX_08 ON T_ADMISSION USING btree( AS_UPDDATE );
CREATE INDEX AS_IDX_09 ON T_ADMISSION USING btree( AS_DELDATE );
