/*================================================
	カテゴリ情報テーブル作成スクリプト
================================================*/

DROP TABLE T_ARTICLE;

CREATE TABLE T_ARTICLE (
	AC_ID		SERIAL	not null primary key,
	AC_CLID		INTEGER,
	AC_STAT		INTEGER,
	AC_CATEID	INTEGER,
	AC_TITLE	TEXT,
	AC_IMG		TEXT,
	AC_IMGORG	TEXT,
	AC_CONTENTS	TEXT,
	AC_DISPNO	INTEGER,
	AC_ADMINID	INTEGER,
	AC_INSDATE	TIMESTAMP,
	AC_UPDDATE	TIMESTAMP,
	AC_DELDATE	TIMESTAMP,
	AC_YOBI1	TEXT,
	AC_YOBI2	TEXT,
	AC_YOBI3	TEXT,
	AC_YOBI4	TEXT,
	AC_YOBI5	TEXT
);

REVOKE all ON T_ARTICLE FROM public;

CREATE INDEX AC_IDX_01 ON T_ARTICLE USING btree( AC_ID );
CREATE INDEX AC_IDX_02 ON T_ARTICLE USING btree( AC_CLID );
CREATE INDEX AC_IDX_03 ON T_ARTICLE USING btree( AC_STAT );
CREATE INDEX AC_IDX_04 ON T_ARTICLE USING btree( AC_CATEID );
CREATE INDEX AC_IDX_05 ON T_ARTICLE USING btree( AC_DISPNO );
CREATE INDEX AC_IDX_06 ON T_ARTICLE USING btree( AC_ADMINID );
CREATE INDEX AC_IDX_07 ON T_ARTICLE USING btree( AC_INSDATE );
CREATE INDEX AC_IDX_08 ON T_ARTICLE USING btree( AC_UPDDATE );
CREATE INDEX AC_IDX_09 ON T_ARTICLE USING btree( AC_DELDATE );
