/*================================================
	カテゴリ情報テーブル作成スクリプト
================================================*/

DROP TABLE T_CATEGORY;

CREATE TABLE T_CATEGORY (
	CG_ID		SERIAL	not null primary key,
	CG_CLID		INTEGER,
	CG_STAT		INTEGER,
	CG_TYPE		INTEGER,
	CG_TOPFLG	INTEGER,
	CG_STITLE	TEXT,
	CG_LTITLE	TEXT,
	CG_DISPNO	INTEGER,
	CG_ADMINID	INTEGER,
	CG_INSDATE	TIMESTAMP,
	CG_UPDDATE	TIMESTAMP,
	CG_DELDATE	TIMESTAMP,
	CG_YOBI1	TEXT,
	CG_YOBI2	TEXT,
	CG_YOBI3	TEXT,
	CG_YOBI4	TEXT,
	CG_YOBI5	TEXT
);

REVOKE all ON T_CATEGORY FROM public;

CREATE INDEX CG_IDX_01 ON T_CATEGORY USING btree( CG_ID );
CREATE INDEX CG_IDX_02 ON T_CATEGORY USING btree( CG_CLID );
CREATE INDEX CG_IDX_03 ON T_CATEGORY USING btree( CG_STAT );
CREATE INDEX CG_IDX_04 ON T_CATEGORY USING btree( CG_TYPE );
CREATE INDEX CG_IDX_05 ON T_CATEGORY USING btree( CG_TOPFLG );
CREATE INDEX CG_IDX_06 ON T_CATEGORY USING btree( CG_DISPNO );
CREATE INDEX CG_IDX_07 ON T_CATEGORY USING btree( CG_ADMINID );
CREATE INDEX CG_IDX_08 ON T_CATEGORY USING btree( CG_INSDATE );
CREATE INDEX CG_IDX_09 ON T_CATEGORY USING btree( CG_UPDDATE );
CREATE INDEX CG_IDX_10 ON T_CATEGORY USING btree( CG_DELDATE );
