/*================================================
	キャンペーン情報テーブル作成スクリプト
================================================*/

DROP TABLE T_CAMPAIN;

CREATE TABLE T_CAMPAIN (
	CP_ID		SERIAL	not null primary key,
	CP_CLID		INTEGER,
	CP_STAT		INTEGER,
	CP_FLG		INTEGER,
	CP_START	TIMESTAMP,
	CP_END		TIMESTAMP,
	CP_CAMSTART	TIMESTAMP,
	CP_CAMEND	TIMESTAMP,
	CP_CGID		INTEGER,
	CP_TITLE	TEXT,
	CP_SUBTITLE	TEXT,
	CP_LINKTEXT	TEXT,
	CP_BTNTEXT	TEXT,
	CP_CONTENTS	TEXT,
	CP_AGE		INTEGER,
	CP_BKGDIMG	TEXT,
	CP_BKGDIMGORG	TEXT,
	CP_IMG1		TEXT,
	CP_IMGORG1	TEXT,
	CP_IMG2		TEXT,
	CP_IMGORG2	TEXT,
	CP_IMG3		TEXT,
	CP_IMGORG3	TEXT,
	CP_IMG4		TEXT,
	CP_IMGORG4	TEXT,
	CP_IDO		DOUBLE PRECISION,
	CP_KEIDO	DOUBLE PRECISION,
	CP_ZOOM		INTEGER,
	CP_ADMINID	INTEGER,
	CP_INSDATE	TIMESTAMP,
	CP_UPDDATE	TIMESTAMP,
	CP_DELDATE	TIMESTAMP,
	CP_YOBI1	TEXT,
	CP_YOBI2	TEXT,
	CP_YOBI3	TEXT,
	CP_YOBI4	TEXT,
	CP_YOBI5	TEXT
);

REVOKE all ON T_CAMPAIN FROM public;

CREATE INDEX CP_IDX_01 ON T_CAMPAIN USING btree( CP_ID );
CREATE INDEX CP_IDX_02 ON T_CAMPAIN USING btree( CP_CLID );
CREATE INDEX CP_IDX_03 ON T_CAMPAIN USING btree( CP_STAT );
CREATE INDEX CP_IDX_04 ON T_CAMPAIN USING btree( CP_FLG );
CREATE INDEX CP_IDX_05 ON T_CAMPAIN USING btree( CP_START );
CREATE INDEX CP_IDX_06 ON T_CAMPAIN USING btree( CP_END );
CREATE INDEX CP_IDX_07 ON T_CAMPAIN USING btree( CP_CAMSTART );
CREATE INDEX CP_IDX_08 ON T_CAMPAIN USING btree( CP_CAMEND );
CREATE INDEX CP_IDX_09 ON T_CAMPAIN USING btree( CP_CGID );
CREATE INDEX CP_IDX_10 ON T_CAMPAIN USING btree( CP_AGE );
CREATE INDEX CP_IDX_11 ON T_CAMPAIN USING btree( CP_IDO );
CREATE INDEX CP_IDX_12 ON T_CAMPAIN USING btree( CP_KEIDO );
CREATE INDEX CP_IDX_13 ON T_CAMPAIN USING btree( CP_ZOOM );
CREATE INDEX CP_IDX_14 ON T_CAMPAIN USING btree( CP_ADMINID );
CREATE INDEX CP_IDX_15 ON T_CAMPAIN USING btree( CP_INSDATE );
CREATE INDEX CP_IDX_16 ON T_CAMPAIN USING btree( CP_UPDDATE );
CREATE INDEX CP_IDX_17 ON T_CAMPAIN USING btree( CP_DELDATE );
