/*================================================
	カテゴリ情報テーブル作成スクリプト
================================================*/

DROP TABLE T_COURSE;

CREATE TABLE T_COURSE (
	CS_ID		SERIAL	not null primary key,
	CS_CLID		INTEGER,
	CS_STAT		INTEGER,
	CS_CGID		INTEGER,
	CS_TITLE	TEXT,
	CS_JTITLE	TEXT,
	CS_ORGANIZE	TEXT,

	CS_PRICE	TEXT,
	CS_ENTRANCE	TEXT,
	CS_SHISETSU	TEXT,
	CS_TEXTFEE	TEXT,
	CS_MONTHLYFEE	TEXT,
	CS_AGE		INTEGER,
	CS_LEVEL	INTEGER,
	CS_PURPOSE	INTEGER,
	CS_SUBJECT	INTEGER,
	CS_PR		TEXT,
	CS_TCID		INTEGER,
	CS_TCFLG	INTEGER,
	CS_IMG1		TEXT,
	CS_IMGORG1	TEXT,
	CS_IMG2		TEXT,
	CS_IMGORG2	TEXT,
	CS_IMG3		TEXT,
	CS_IMGORG3	TEXT,
	CS_IMG4		TEXT,
	CS_IMGORG4	TEXT,
	CS_IMG5		TEXT,
	CS_IMGORG5	TEXT,
	CS_DISPNO	INTEGER,

	CS_ADMINID	INTEGER,
	CS_INSDATE	TIMESTAMP,
	CS_UPDDATE	TIMESTAMP,
	CS_DELDATE	TIMESTAMP,
	CS_YOBI1	TEXT,
	CS_YOBI2	TEXT,
	CS_YOBI3	TEXT,
	CS_YOBI4	TEXT,
	CS_YOBI5	TEXT
);

REVOKE all ON T_COURSE FROM public;

CREATE INDEX CS_IDX_01 ON T_COURSE USING btree( CS_ID );
CREATE INDEX CS_IDX_02 ON T_COURSE USING btree( CS_CLID );
CREATE INDEX CS_IDX_03 ON T_COURSE USING btree( CS_STAT );
CREATE INDEX CS_IDX_04 ON T_COURSE USING btree( CS_CGID );
CREATE INDEX CS_IDX_05 ON T_COURSE USING btree( CS_AGE );
CREATE INDEX CS_IDX_06 ON T_COURSE USING btree( CS_LEVEL );
CREATE INDEX CS_IDX_07 ON T_COURSE USING btree( CS_PURPOSE );
CREATE INDEX CS_IDX_08 ON T_COURSE USING btree( CS_SUBJECT );
CREATE INDEX CS_IDX_09 ON T_COURSE USING btree( CS_TCID );
CREATE INDEX CS_IDX_10 ON T_COURSE USING btree( CS_TCFLG );
CREATE INDEX CS_IDX_11 ON T_COURSE USING btree( CS_DISPNO );
CREATE INDEX CS_IDX_12 ON T_COURSE USING btree( CS_ADMINID );
CREATE INDEX CS_IDX_13 ON T_COURSE USING btree( CS_INSDATE );
CREATE INDEX CS_IDX_14 ON T_COURSE USING btree( CS_UPDDATE );
CREATE INDEX CS_IDX_15 ON T_COURSE USING btree( CS_DELDATE );
