/*================================================
	カテゴリ情報テーブル作成スクリプト
================================================*/

DROP TABLE T_CSARTICLE;

CREATE TABLE T_CSARTICLE (
	CSA_ID		SERIAL	not null primary key,
	CSA_CSID	INTEGER,
	CSA_STAT	INTEGER,
	CSA_CATEID	INTEGER,
	CSA_TITLE	TEXT,
	CSA_IMG		TEXT,
	CSA_IMGORG	TEXT,
	CSA_CONTENTS	TEXT,
	CSA_DISPNO	INTEGER,
	CSA_ADMINID	INTEGER,
	CSA_INSDATE	TIMESTAMP,
	CSA_UPDDATE	TIMESTAMP,
	CSA_DELDATE	TIMESTAMP,
	CSA_YOBI1	TEXT,
	CSA_YOBI2	TEXT,
	CSA_YOBI3	TEXT,
	CSA_YOBI4	TEXT,
	CSA_YOBI5	TEXT
);

REVOKE all ON T_CSARTICLE FROM public;

CREATE INDEX CSA_IDX_01 ON T_CSARTICLE USING btree( CSA_ID );
CREATE INDEX CSA_IDX_02 ON T_CSARTICLE USING btree( CSA_CSID );
CREATE INDEX CSA_IDX_03 ON T_CSARTICLE USING btree( CSA_STAT );
CREATE INDEX CSA_IDX_04 ON T_CSARTICLE USING btree( CSA_CATEID );
CREATE INDEX CSA_IDX_05 ON T_CSARTICLE USING btree( CSA_DISPNO );
CREATE INDEX CSA_IDX_06 ON T_CSARTICLE USING btree( CSA_ADMINID );
CREATE INDEX CSA_IDX_07 ON T_CSARTICLE USING btree( CSA_INSDATE );
CREATE INDEX CSA_IDX_08 ON T_CSARTICLE USING btree( CSA_UPDDATE );
CREATE INDEX CSA_IDX_09 ON T_CSARTICLE USING btree( CSA_DELDATE );
