/*================================================
	基本メニュー情報テーブル作成スクリプト
================================================*/

DROP TABLE T_MENU;

CREATE TABLE T_MENU (
	MN_ID		SERIAL	not null primary key,
	MN_CLID		INTEGER,
	MN_LSTAT	INTEGER,
	MN_LNAME	TEXT,
	MN_LDISPNO	INTEGER,
	MN_HSTAT	INTEGER,
	MN_HDISPNO	INTEGER,
	MN_HNAME	TEXT,
	MN_HURL		TEXT,
	MN_ADMINID	INTEGER,
	MN_INSDATE	TIMESTAMP,
	MN_UPDDATE	TIMESTAMP,
	MN_DELDATE	TIMESTAMP,
	MN_YOBI1	TEXT,
	MN_YOBI2	TEXT,
	MN_YOBI3	TEXT,
	MN_YOBI4	TEXT,
	MN_YOBI5	TEXT
);

REVOKE all ON T_MENU FROM public;

CREATE INDEX MN_IDX_01 ON T_MENU USING btree( MN_ID );
CREATE INDEX MN_IDX_02 ON T_MENU USING btree( MN_CLID );
CREATE INDEX MN_IDX_03 ON T_MENU USING btree( MN_LSTAT );
CREATE INDEX MN_IDX_04 ON T_MENU USING btree( MN_LDISPNO );
CREATE INDEX MN_IDX_05 ON T_MENU USING btree( MN_HSTAT );
CREATE INDEX MN_IDX_06 ON T_MENU USING btree( MN_HDISPNO );
CREATE INDEX MN_IDX_07 ON T_MENU USING btree( MN_ADMINID );
CREATE INDEX MN_IDX_08 ON T_MENU USING btree( MN_INSDATE );
CREATE INDEX MN_IDX_09 ON T_MENU USING btree( MN_UPDDATE );
CREATE INDEX MN_IDX_10 ON T_MENU USING btree( MN_DELDATE );
