/*================================================
	カテゴリ情報テーブル作成スクリプト
================================================*/

DROP TABLE T_QA;

CREATE TABLE T_QA (
	QA_ID		SERIAL	not null primary key,
	QA_CLID		INTEGER,
	QA_STAT		INTEGER,
	QA_CGID		INTEGER,
	QA_QUESTION	TEXT,
	QA_ANSWER	TEXT,
	QA_DISPNO	INTEGER,
	QA_ADMINID	INTEGER,
	QA_INSDATE	TIMESTAMP,
	QA_UPDDATE	TIMESTAMP,
	QA_DELDATE	TIMESTAMP,
	QA_YOBI1	TEXT,
	QA_YOBI2	TEXT,
	QA_YOBI3	TEXT,
	QA_YOBI4	TEXT,
	QA_YOBI5	TEXT
);

REVOKE all ON T_QA FROM public;

CREATE INDEX QA_IDX_01 ON T_QA USING btree( QA_ID );
CREATE INDEX QA_IDX_02 ON T_QA USING btree( QA_CLID );
CREATE INDEX QA_IDX_03 ON T_QA USING btree( QA_STAT );
CREATE INDEX QA_IDX_04 ON T_QA USING btree( QA_CGID );
CREATE INDEX QA_IDX_05 ON T_QA USING btree( QA_DISPNO );
CREATE INDEX QA_IDX_06 ON T_QA USING btree( QA_ADMINID );
CREATE INDEX QA_IDX_07 ON T_QA USING btree( QA_INSDATE );
CREATE INDEX QA_IDX_08 ON T_QA USING btree( QA_UPDDATE );
CREATE INDEX QA_IDX_09 ON T_QA USING btree( QA_DELDATE );
