/*================================================
	教室基本情報テーブル作成スクリプト
================================================*/

DROP TABLE T_SCHOOL;

CREATE TABLE T_SCHOOL (
	SC_ID		SERIAL	not null primary key,
	SC_CLID		INTEGER,
	SC_STAT		INTEGER,
	SC_TITLE	TEXT,
	SC_KEYWD	TEXT,
	SC_INTRODUCE	TEXT,
	SC_CLR		INTEGER,
	SC_UPD		TIMESTAMP,
	SC_MASTER	TEXT,
	SC_POSITION	TEXT,
	SC_AGE		TEXT,
	SC_CLASSFORM	TEXT,
	SC_RESULTS	TEXT,
	SC_STUDENTS	TEXT,
	SC_START	TIMESTAMP,
	SC_END		TIMESTAMP,
	SC_HOLIDAY	TEXT,
	SC_HP		TEXT,
	SC_ENTRYMAIL	TEXT,
	SC_INFOMAIL	TEXT,
	SC_MOVIE	TEXT,
	SC_LOGO		TEXT,
	SC_LOGOORG	TEXT,
	SC_TOPIMG	TEXT,
	SC_TOPIMGORG	TEXT,
	SC_IMG1		TEXT,
	SC_IMGORG1	TEXT,
	SC_IMG2		TEXT,
	SC_IMGORG2	TEXT,
	SC_IMG3		TEXT,
	SC_IMGORG3	TEXT,
	SC_IMG4		TEXT,
	SC_IMGORG4	TEXT,
	SC_MAPIMG	TEXT,
	SC_MAPIMGORG	TEXT,
	SC_PR		TEXT,
	SC_RHTML	TEXT,
	SC_LHTML	TEXT,
	SC_IDO		DOUBLE PRECISION,
	SC_KEIDO	DOUBLE PRECISION,
	SC_ZOOM		INTEGER,
	SC_PRIVACY	TEXT,
	SC_ADMINID	INTEGER,
	SC_INSDATE	TIMESTAMP,
	SC_UPDDATE	TIMESTAMP,
	SC_DELDATE	TIMESTAMP,
	SC_YOBI1	TEXT,
	SC_YOBI2	TEXT,
	SC_YOBI3	TEXT,
	SC_YOBI4	TEXT,
	SC_YOBI5	TEXT
);

REVOKE all ON T_SCHOOL FROM public;

CREATE INDEX SC_IDX_01 ON T_SCHOOL USING btree( SC_ID );
CREATE INDEX SC_IDX_02 ON T_SCHOOL USING btree( SC_CLID );
CREATE INDEX SC_IDX_03 ON T_SCHOOL USING btree( SC_STAT );
CREATE INDEX SC_IDX_04 ON T_SCHOOL USING btree( SC_UPD );
CREATE INDEX SC_IDX_05 ON T_SCHOOL USING btree( SC_AGE );
CREATE INDEX SC_IDX_06 ON T_SCHOOL USING btree( SC_CLASSFORM );
CREATE INDEX SC_IDX_07 ON T_SCHOOL USING btree( SC_RESULTS );
CREATE INDEX SC_IDX_08 ON T_SCHOOL USING btree( SC_STUDENTS );
CREATE INDEX SC_IDX_09 ON T_SCHOOL USING btree( SC_START );
CREATE INDEX SC_IDX_10 ON T_SCHOOL USING btree( SC_END );
CREATE INDEX SC_IDX_11 ON T_SCHOOL USING btree( SC_IDO );
CREATE INDEX SC_IDX_12 ON T_SCHOOL USING btree( SC_KEIDO );
CREATE INDEX SC_IDX_13 ON T_SCHOOL USING btree( SC_ZOOM );
CREATE INDEX SC_IDX_14 ON T_SCHOOL USING btree( SC_ADMINID );
CREATE INDEX SC_IDX_15 ON T_SCHOOL USING btree( SC_INSDATE );
CREATE INDEX SC_IDX_16 ON T_SCHOOL USING btree( SC_UPDDATE );
CREATE INDEX SC_IDX_17 ON T_SCHOOL USING btree( SC_DELDATE );
