/*================================================
	講師マスタ情報テーブル作成スクリプト
================================================*/

DROP TABLE T_TEACHER;

CREATE TABLE T_TEACHER (
	TC_ID		SERIAL	not null primary key,
	TC_CPID		INTEGER,
	TC_STAT		INTEGER,
	TC_NAME		TEXT,
	TC_IMG		TEXT,
	TC_IMGORG	TEXT,
	TC_CONTENTS	TEXT,
	TC_COMMENT	TEXT,
	TC_SUBJECT	TEXT,
	TC_AGE		INTEGER,
	TC_ADMINID	INTEGER,
	TC_INSDATE	TIMESTAMP,
	TC_UPDDATE	TIMESTAMP,
	TC_DELDATE	TIMESTAMP,
	TC_YOBI1	TEXT,
	TC_YOBI2	TEXT,
	TC_YOBI3	TEXT,
	TC_YOBI4	TEXT,
	TC_YOBI5	TEXT
);

REVOKE all ON T_TEACHER FROM public;

CREATE INDEX TC_IDX_01 ON T_TEACHER USING btree( TC_ID );
CREATE INDEX TC_IDX_02 ON T_TEACHER USING btree( TC_CPID );
CREATE INDEX TC_IDX_03 ON T_TEACHER USING btree( TC_STAT );
CREATE INDEX TC_IDX_04 ON T_TEACHER USING btree( TC_AGE );
CREATE INDEX TC_IDX_05 ON T_TEACHER USING btree( TC_ADMINID );
CREATE INDEX TC_IDX_06 ON T_TEACHER USING btree( TC_INSDATE );
CREATE INDEX TC_IDX_07 ON T_TEACHER USING btree( TC_UPDDATE );
CREATE INDEX TC_IDX_08 ON T_TEACHER USING btree( TC_DELDATE );
